# Site settings
title: Pasha's Blog
header-img: img/home-bg.jpg
email: pasha.nitw@gmail.com
description: "Write your site description here. It will be used as your sites meta description as well!"
baseurl: ""
url: "http://yourdomain.com"
twitter_username: pashapluss
github_username:  pashanitw
facebook_username:  pasha.nitw

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
